GHCUP_INSTALL_BASE_PREFIX=/opt/ghc
export GHCUP_INSTALL_BASE_PREFIX

CABAL_DIR=${GHCUP_INSTALL_BASE_PREFIX}/cabal
export CABAL_DIR

PATH=${CABAL_DIR}/bin:${GHCUP_INSTALL_BASE_PREFIX}/.ghcup/bin:${PATH}
export PATH
